name: Traefik
description: Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
url: https://github.com/charlestephen/hassio-addons/tree/main/traefik
version: 1.0.0
stage: stable
slug: traefik
codenotary: notary@home-assistant.io
startup: system
init: false
boot: auto
hassio_role: default
hassio_api: true
auth_api: true
ingress: true
ingress_entry: dashboard/
panel_icon: mdi:earth-arrow-right
ports:
  80/tcp: 80
  443/tcp: 443
  8080/tcp: 8080
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  8080/tcp: Traefik
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
image: "ghcr.io/charlestephen/hassio-addons/traefik-{{ arch }}:{{ version }}"
map:
- addon_config:rw
- ssl:rw
options:
  custom_config: false
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
dynamic_configuration_path: /config/traefik/dynamic/
  letsencrypt:
    enabled: false
    resolvers: []
  metrics:
    enabled: true
  env_vars: []
schema:
  custom_config: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
    - str?
  metrics:
    enabled: bool
  env_vars:
  - str