build_from:
  amd64: ghcr.io/hassio-addons/addon-base-nodejs:0.2.2
  aarch64: ghcr.io/hassio-addons/addon-base-nodejs:0.2.2
  armv7: ghcr.io/hassio-addons/addon-base-nodejs:0.2.2
  armhf: ghcr.io/hassio-addons/addon-base-nodejs:0.2.2
  i386: ghcr.io/hassio-addons/addon-base-nodejs:0.2.2
